#+TITLE: Практикум 3 курс. Осень 16-17. Задание 2
#+OPTIONS: toc:nil

* Описание
  В этом задании вам предстоит провести анализ некоторого временного ряда и попробовать предсказать значения для последующих месяцев.
  В рамках данного задания мы:
  - научимся правильно считывать данные и их визуализировать;
  - поймем как определять свойства временных рядов и познакомимся с различными моделями для предсказания значений;
  - оценим качество полученных моделей.

  Цель * задания 2 * в том, чтобы продолжить ваше изучение языка Python, попутно познакомиться с такими библиотеками, как Pandas(работа с данными), statsmodels(работа с различными статистическими моделями, в том числе и временными рядами).

  Что вам предстоит сделать:
  1. Считать данные из data.csv разделить их на два ~Dataframe~: основную выборку(80%) и тестовую(20%). Ответы на тестовой выборке не следует использовать ни в каких экспериментах, кроме финального.
  2. Проверить является ли ряд стационарным в широком смысле. Это можно сделать двумя способами: 
    1. Провести визуальную оценку, отрисовав ряд и скользящую статистику(среднее, стандартное отклонение). Постройте график на котором будет отображен сам ряд и различные скользящие статистики.
    2. Провести тест Дики - Фуллера.
  Сделать выводы из полученных результатов. Оценить достоверность статистики.
  3. Разложить временной ряд на тренд, сезональность, остаток в соответствии с аддитивной, мультипликативной моделями. Визуализировать их, оценить стационарность получившихся рядов, сделать выводы.
  4. 
  ...
  8. Обучить вашу модель на основной выборке и предсказать значения тестовой. Оценить качество модели.

* Сдача
  Задание *должно* выполнять группой ...
  Процесс стандартный, и описан в ~README.org~, секция [[file:~/../../README.org::#submission-rules][Выполнение и сдача заданий]].

* Сроки
- Сдача до * * 2016г.
- Прохождение ревью до * * 2016г.

